### ISSUE TITLE
Scroll should un-focus URL bar

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#108]
Or alternative: focus could instead keep URL bar visible. @Gozala whichever you think is best.

**Comment by Gozala** [comment]
@paulrouget I wanted to tackle this one, but I'm afraid I was unable to figure out how our address bar is even happens to appear / disappear. I would like to add something like `navigationPanel: {isActive: false}` to a global state where `isActive` is true if bar is visible and `false` if hidden.

**Comment by Gozala** [comment]
@paulrouget ok I think I found what I was looking for, also have submitted #143 to fix it.

**Comment by paulrouget** [comment]
Yeah, you need to do that on scroll. But that won't work well once we will switch to apzc. Well… maybe it would. I don't exactly know how it works: does a scroll event handler will make apzc bail or just call the listener later?

(I asked the question, I'll edit later once I know)

> Scroll should un-focus URL bar or focus could instead keep URL bar visible

@gordonbrander we need to know what's best, because it's really 2 different strategies.

**Comment by gordonbrander** [comment]
I think "focus should instead keep URL bar visible" is better.

But, __I think we should defer this item__.
I'm looking at it in the current version of master and with other interaction bugs fixed, it's a very minor issue at best. I don't feel it will impact the MVP.

**Comment by paulrouget** [comment]
(We can use `onscroll`)

**Comment by Gozala** [comment]
so here is a second implementation that keeps url bar instead. I personally find loose focus on scroll behavior a lot more.

**Comment by gordonbrander** [comment]
Closed by https://github.com/mozilla/browser.html/commit/088648802150e5c17493ac90ede40ac86292c71b
