### ISSUE TITLE
Full tab model

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#112]
Implement full tab model as designed.

In this model each domain is a tab. In fact, tabs aren't so much tabs as "active sites", in the same way that the task manager on iOS is your "active apps".

- New tabs are automatically opened for each root domain.
  - Clicking a link will either open a page in-place, or, if domain is different, it will open a new tab.
  - Exception: search pages belong to the tab who's page they open. They do not have a separate tab.
- You can open multiple tabs for the same domain the same way you do today: right click -> open in new tab, or cmd+click.
- Each tab has its own history stack (same as today). You can navigate it using controls in location bar.
- Tabs are ordered by last access from right to left, with the most recent at the far right.
- Hitting back on a tab that has no more "back" will transition leftward to the tab before it.
- After tabs fill the screen, old ones fall off. However they can be quickly brought back via tab search or dashboard.

Design rational
---------------------

Hypothesis: tabs today do many things, all poorly:

- Multitasking
- A place to dock a background task (music, email)
- Bookmark "limbo"

As a result:

- Tabs have to be organized by hand
- Tab explosion
- When one window fills up with tabs another has to be opened up. It's a windowing system that relies on another windowing system to function.
- Tabs are a windowing system. The browser is an OS. We need a richer interaction model than X-axis to be able to create a fully immersive browser that can disrupt use of the host OS.

Try:

- Fixing the multitasking case by focusing on the goal: quickly switching between 2-8ish of your most recently used sites.
- Later: supplement  with a tab dashboard that represents your full browsing history for the day. This should solve the "bookmark limbo" case.
- cmd+t new tab. cmd+shift+t switch tabs.

Why:

- Alt+tab, iOS multitasker and WebOS cards are all very successful multitasking  models because they self-organize. Both use the same interaction model:  your recently used active apps are always at the front.
- People think in domains. Let's organize pages by domain.
  - An app is a container for a branded experience.
  - A TV channel is a container for a branded experience.
  - Likewise a domain (facebook.com) is a container for a branded experience.
  - Analogy: dashboard is your inventory, tabs are your loadout.

Desired outcomes / questions we want to answer:

- How does task switching and clustering by domain feel during actual browsing?
- Be able to use the browser in a limited fashion.
- We will try another approach if: Gordon and Paul both think it's terrible.

**Comment by Gozala** [comment]
me and @gordonbrander spend quite some time looking into the issue that was reproducible by clicking `control tab` keys really fast. We had different guess what could have being cousin it & there is an archive of the discussion here https://browserhtml.slack.com/archives/general/p1424744707000607


After looking into this further, I can say I have a logical explanation of observed behavior. This is what is going on there. To start with here a trace of the events when the bug occurs:

```js
// 1. ! render
{ tabStrip: {isActive: false},
  webViewers: [{id: 0, isSelected: true, isActive: true },
               {id: 1, isSelected: false, isActive: false}]}

// 2. ! keydown: 'control tab' @ 397537859

// 3. ! update in .webViewers
{ tabStrip: {isActive: false},
  webViewers: [{id: 0, isSelected: false, isActive: true },
               {id: 1, isSelected: true, isActive: false}]}

// 4. ! update in .tabStrip.isActive
{ tabStrip: {isActive: true},
  webViewers: [{id: 0, isSelected: false, isActive: true },
               {id: 1, isSelected: true, isActive: false}]}

// 5. ! keyup: 'control' @ 397537915

// 6. ! update in .tabStrip.isActive
{ tabStrip: {isActive: false},
  webViewers: [{id: 0, isSelected: false, isActive: true },
               {id: 1, isSelected: true, isActive: false}]}

// 7. ! keyup: 'tab' @ 397537962

// 8. ! render
{ tabStrip: {isActive: false},
  webViewers: [{id: 0, isSelected: false, isActive: true },
               {id: 1, isSelected: true, isActive: false}]}
```

Here is an explanation of the trace of events:

1.  First normal stat was rendered, where tabstrip isn't visible and first tab is both selected and active.
2. `control tab` key was pressed.
3. `control tab` key handler triggered an update in the `webViewers` that marked first tab unselected and second one selected.
4. `control tab` key handler toggled a tabstrip visibility, causing a `.tabStrip.isActive` to become `true`.
5. `control` key was released.
6. `control` keyup handler was triggered which toggled tabstrip visibility, causing a `.tabStrip.isActive` to become `false`.
7. `tab` key was released.
8. Request animation finally caused rendering of a new state.

Clearly there is a an update missing that would flip `isActive` field of both tabs. The it was not filed is because code doing it invokes `webViewersCursor.update(activate)` which in turns find tabs that has `isActive: true` and sets it to `false` & also finds a tab that has `isSelected: true` and makes it's `isActive: true`. Anyway what happens is that because keyup event handler happened before render did, all the event handlers were still bound to a state from a previous render, where `isActive` and `isSelected` where true on the same tab, there for `activate` did nothing, which is why there was no update for it in the trace & also why we end up rendering incorrect state.

**Comment by Gozala** [comment]
So immediate solution that would work would be to disable animation frame and cause render loop right away, that way render will be triggered before `keyup` handlers will and there for keyup handler will have a pointer to an up to date state.

Which is what I'm going to do for now, while seeking a solution how to fix this with animation frame enabled.

**Comment by gordonbrander** [comment]
@Gozala these comments belong to https://github.com/mozilla/browser.html/issues/82, not this bug.

**Comment by gordonbrander** [comment]
The true model is at risk. Risk mitigation..?
Short-term fix: let's try to re-order ordinary tabs by last access.

**Comment by Gozala** [comment]
http://www.azarask.in/blog/post/solving-the-alt-tab-problem/

**Comment by gordonbrander** [comment]
^ Great ideas, but I'm not sure I agree with the proposed solution. Invisible rules that change over time are confusing. Alternatives:

- Search can be a great solution for this type of thing because it breaks with spacial memory completely
- Or, have a "sticky" section that doesn't change containing your favorite/most used items. This is what the OSX dock does.
