### ISSUE TITLE
Huge stack on every RFA

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#159]
I honestly don't know if this is bad or not:

![rfa](https://cloud.githubusercontent.com/assets/373579/6408301/b588bdc2-be51-11e4-9c83-124370dd258c.png)

Here is the whole stack:

![allstack](https://cloud.githubusercontent.com/assets/373579/6408392/9ef5947a-be53-11e4-9e45-1be48ca11bd9.png)

This is how we animate the progressbar:
- on each RFA
- calculate the progress
- change opacity and translate

So in a non-react way, on each RFA, we would have a very short stack (one or two functions). Here we have these giant stacks just to change opacity and translate.

Can we ignore that? Is having a big stack a real problem?

I  will investigate more, especially figuring out what exactly takes time in this RFA. I think JS itself is negligible.

**Comment by Gozala** [comment]
Here is few things to consider:

1. Long stack traces are not that unusual with large frameworks like react, although I can't tell if in this case those are too long. Overall on stacks are not a problem, that not to say we don't have a problem here.

2.  We use dev build of react that has ton of extra stuff for example all the `ReactPerf` entries in stack are from there, if we used a production (minimised) build instead stacks would be shorter & react would also be faster. Here is the quote from their website:

  > The dev build of React is slower than the prod build, due to all the extra logic for providing, for example, React's friendly console warnings (stripped away in the prod build). Therefore, the profiler only serves to indicate the relatively expensive parts of your app.

3. People using react tend to use it's performance tools to get a better insight on where time is spend. It's usually gives more cleaner picture than plain profiler, please check out this page that describes how they can be used: https://facebook.github.io/react/docs/perf.html

4. Maybe we could have two manifests in the app one for production other for development. Dev version would load dev builds of react etc.., while production one will use production builds.

5. As I mentioned elsewhere I took a quick look at what components get re-triggered during progress updates by running this into console `require('omniscient').debug()`([see docs](http://omniscientjs.github.io/api/01-omniscient-api-reference/#omniscientdebugpattern) on how to use it) and I noticed that we ret-trigger few that do not need to be triggered:
  > ```
"<Deck key=tabstrip>: render" omniscient.js:2021:27
"<Tab key=4865e852-3e23-4c57-b4dc-e01d65ade060>: render" omniscient.js:2021:27
"<Deck key=web-viewers>: render" omniscient.js:2021:27
"<WebViewer key=4865e852-3e23-4c57-b4dc-e01d65ade060>: render"
```

The reason they are triggered is because progress state info lives in the `webViewer` so any time one is updated it would trigger both Tabstrip and WebViewer decks and also a `Tab` and `WebViewer` components associated with that `webViewer`.  This could be resolved by passing only subset of `webViewers` info to a decks, by mapping and extracting only relevant info. Or alternatively storing progress data in the root of the state. For example we could have `progress: {webViewerId: progressValue}` in the root of the state that way cursor to the relevant progress will be passed only to a progress component.

**Comment by Gozala** [comment]
On the unrelated matter, I think block boxing for the profiler would be really great!

**Comment by paulrouget** [comment]
Apparently, there's no reason to be worried about that.
