### ISSUE TITLE
mediaQueries in Graphene are all messed up

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#185]
Load http://daringfireball.net in Graphene runner. Font looks about 1.75x ~ 2x that of Firefox.

**Comment by paulrouget** [comment]
Not font inflation. It's clearly disabled.

**Comment by gordonbrander** [comment]
Wild guess: maybe a mobile stylesheet? What does our UA look like?

**Comment by paulrouget** [comment]
It's because of: `max-device-width: 480px`. I think I know why this is happening.

**Comment by paulrouget** [comment]
![screen shot 2015-03-05 at 04 21 34](https://cloud.githubusercontent.com/assets/373579/6498687/2ea14214-c2ef-11e4-96e1-103ca9b19046.png)

**Comment by paulrouget** [comment]
Left, graphene, right, firefox desktop.

**Comment by paulrouget** [comment]
I'm not sure yet what's going on. I'm guessing gecko is trying to use `hal` to get these values. We should check which screen implementation is used. For example: `widget/cocoa/nsScreenCocoa.mm#116` or `widget/PuppetWidget.cpp#1024`? I'll look at this later.

**Comment by paulrouget** [comment]
Note for later: check which implementation of `::GetPrimaryScreen` is executed.

**Comment by fabricedesre** [comment]
That's because we have font.size.inflation.minTwips equals to 120 in b2g. I'll set it to 0 in graphene.

**Comment by fabricedesre** [comment]
Hm, changing minTwips doesn't help.

**Comment by paulrouget** [comment]
@fabricedesre Already did that. See part 2 of bug 1134106.

**Comment by fabricedesre** [comment]
I investigated a bit more:
https://mxr.mozilla.org/mozilla-central/source/gfx/src/nsDeviceContext.cpp#617 returns an empty rect because mWidget is null at https://mxr.mozilla.org/mozilla-central/source/gfx/src/nsDeviceContext.cpp#648
This is because we don't have a real widget in content processes... If we disable OOP then everything is as expected.
I'll file a gecko bug and ask people that know about that part of the code.

**Comment by paulrouget** [comment]
Works now.
