### ISSUE TITLE
Determine update method

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#209]
- We should have instant startup
- We should be able to update the UI on startup
  - Push updates?
- Caching approach... how do we mark interface dirty?

cc @paulrouget @Gozala

**Comment by paulrouget** [comment]
@fabricedesre knows better, and he's working on that.

**Comment by gordonbrander** [comment]
@gordonbrander need to design a notification style so we can tell user "update available".

**Comment by fabricedesre** [comment]
So we have two pieces:
- updates of the runtime. This has landed, and updates are silently downloaded applied on restart. We could trigger a notification when updates are available. I didn't add that because there was no UI ready.

- updates of the front-end.  Currently this works by hitting F5.
We can do something like what Gordon describes (except the "don't reload iframes"), likely with a less aggressive polling. What I don't like here is that we need to maintain this "version file", and that's as error prone as an appcache manifest ;). If the version file can be autogenerated when pushing to gh-pages that would be nice.

A longer term option would be to use the push notifications api, and ensure that every time we push to gh-pages, me also trigger a push notification and use it to force refresh.

Overall, I wonder why just relying on http caching semantics is not good enough. This is what web sites are using... and we don't use any special caching rules for browser.html, so I would expect us to get the right version on every restart. Long lived session still need a solution though.

**Comment by gordonbrander** [comment]
+1 on using HTTP caching if possible.

Regarding front-end, silent-update-on-restart is pretty good, but we would like to update in-app as a demonstration of what the technology can do.

When you do have to push an update to users, this type of mechanism is also a big improvement over the "we have updates -> restart" flow that we often force on users now. We could limit restarts to rendering engine updates, and even then only do it silently.

**Comment by gordonbrander** [comment]
Closed by https://github.com/mozilla/browser.html/commit/fa1d697dc59e61e0046b5684c72c7fc95d984143
