### ISSUE TITLE
Pages title in dashboard should show up in the urlbar, not under the tiles

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#216]
For consistency with the tabs, and the future link-preview mechanism.

/cc @gordonbrander

**Comment by gordonbrander** [comment]
Here's the reason the title is under the tile:

Ergonomics:
- With tabs, the visual distance between the location bar and the tab is very small... 20px or  so. You can fit the tab and the title within your field of vision.
- The visual distance between tabs and location bar is much greater. It is unlikely that you can fit both the tab and the location bar within your field of vision. This means you have to move your eye up to the location bar to read the text. Worse still, you could  miss the change completely because it is outside your peripheral vision.

Information architecture:
- The tabs are conceptually supposed to be "part of" the location bar. They reflection the recent things you have done with the location bar.
- The tiles are part of a separate space: a home screen layer "underneath" or "in front of" the websites.

Consistency is great, but context wins over consistency:
https://gettingreal.37signals.com/ch09_Context_Over_Consistency.php
https://signalvnoise.com/posts/628-iphone-context-over-consistency
