### ISSUE TITLE
UX: feedback

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#288]
The UX of browser.html is still very experimental and will change. This is a meta bug to gather comments about the current interface.

**Comment by paulrouget** [comment]
Love:
- the full-page mode feels natural and is beautiful;
- the navbar, when present, is not polluting the content. Very subtle;
- the themes work beautifully; I love it when I open a page that has a theme.

**Comment by paulrouget** [comment]
For reference, here is how **I** use tabs in Firefox:
1. My apps, as pintabs (telegram, irccloud, slacks, 8tracks)
2. Todolist, things I need to work on, read or revisit often (~6 tabs)
3. Tabs open from rss/reddit/hackernews (open HN, cmd-click on 10 links, close HN, go though all the links, after they are all read, all these tabs closed, and I'm back to `1` & `2`. Maybe I save one or two tab to read later, ending up in `2`)

Layout is easy (`[pintabs] [todolist] [temporary tabs]`) and never changes.

----

With browser.html, my main grip is with the tabstrip.

In a regular browser, I can very easily have a glimpse of what tabs are open, and how they are arranged (so what they "mean": app/todo/tmp).

I don't always know exactly where I want to go next. Which tab. So I want to look at the tabstrip, but:
1. there's no easy way to show it. Either move the mouse hover the navbar, which is not easy and slow, or press ctrl-tab, which actually does the job, but it activates the next tab, which makes the current tab not being the active one, which is confusing.
2. the lack of title (you have to active the tab with mouse or keyboard to see) makes it hard to know what the tab is about. Many tabs are similar (multiple google tabs / multiple HN comment threads tabs / multiple bugzilla tabs, …) making it difficult to choose the right tab
3. screenshots don't help me. I'd rather have favicon/touch-icon
4. it is always a surprise to me how the tab will be organized (things keep moving around). The time-based layout is not working with me, maybe because I'm not a "real" mac user.

Not saying we should design the tabstrip for me, but just wanted to share my experience.

**Comment by Gozala** [comment]
> I don't always know exactly where I want to go next. Which tab. So I want to look at the tabstrip, but:
> 1. there's no easy way to show it. Either move the mouse hover the navbar, which is not easy and slow, or press ctrl-tab, which actually does the job, but it activates the next tab, which makes the current tab not being the active one, which is confusing.

Wait so you are saying that `ctrl tab` works but then it activates the tab, isn't that what you were trying to do though ? I though intent was to switch to another tab, so you can keep clicking `ctrl tab` until you discover the one you were looking for and then release to activate.

Just trying to understand what exactly isn't great about `ctrl tab`, I'm under impression that you just trying to look at other tabs without actually switching to any of them are you ? That is actually covered by hovering with a mouse but maybe having keybindings for that would help ?

**Comment by Gozala** [comment]
Here is how **I** use browser which I think is quite different. I am one of the few users of "tab groups" I tend to organise my tabs per subject in a group. For example I'd have groups like:

1. **Trip**
  So first group will contain tabs like airbnb, tripitit for the trip, maybe some flight stuff etc...

2. **Bug I'm working on**
   Bugzilla for the bug, maybe some mxr links, mdn links anything related to helping me resolve that bug.

3. **Research in headphones to buy**
    Amozon link for options, reviews, etc...

Based on my focus I would have one of the groups activated with just the tabs related to that activity. Unfortunately firefox does not make it easy to switch between groups or has a good presentation of tabs in the group. In fact in recent month I have started leveraging pinterest for that. For example I would pin bunch of headphones links, and even reviews and they basically serve as a bookmark gallery rather then actual pics, although pics to do help presentation.

I think for bugzilla activity `ctrl tab` is actually pretty good as that matches my tab switching model pretty well, although not quite sure where `command click` tabs should go as I think I may not like them becoming first or second in the list. Another thing I tend miss at a times is a full url rather then a page summary. Lot of times github links for source files won't have a distinct titles so it's not enough to just see that while trying to switch.

For a trip planning activity, I still would love to have something like pinterest gallery but that I can switch to really fast (unlike in pinterest). In fact now that I think about it I would love to even have some kind of template for such an activity with empty tab cells that I need to fill and mark when the task is complete :) That sounds crazy but usually any planning I have is associated with web activity and a todo list. Most of a time during planning I do keep a todo list and most items will have links associated with them (or maybe not yet) while in progress links are just pointers to things I'm doing / need to do. While for complete items it's more like details. Tripit it kind of tries to do that part but again it has same problem as pinterest, overview is not always enough and if you click a link it takes time to load and often times I end up with duplicate links to the same stuff.


I don't actually use pinned tabs I tried them few times but I find them distracting for my activity based focus. To give you an example IRCCloud & Bugzilla Todos were my pinned tabs but then they would distract me when I do trip planning or headphones research as they were not part of that activity group. 
Another issue is that if I'm working on bug and someone has pinged me on IRC I reply and then I need to find tab I was on. So lately I've being using add-on that installed page as a firefox os APP on my desktop instead of pinned tabs as that does not interfere with my workflow. I imagine that we did pinned tabs such that it would not interfere with my flow I'd use them. For that I expect that switch to pinned tabs does not affect order of tabs in tab switcher, and if we have groups pinned tabs are associated with a group and aren't global.

**Comment by paulrouget** [comment]
> Just trying to understand what exactly isn't great about ctrl tab, I'm under impression that you just trying to look at other tabs without actually switching to any of them are you ?

Yes. Ctrl tab will highlight another tab, so I'm not sure what tab is the current one.

> That is actually covered by hovering with a mouse but maybe having keybindings for that would help ?

I don't use the mouse much, and it's hard to move the pointer exactly in the navbar.
