### ISSUE TITLE
awesomebar regression

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#307]
I'm pretty sure it's a regression due to 6922cf1574cb91228021d6f0349d424984aa2999:

STR:

1. type `f`
2. see: `flickr.com`, `forbes.com` and `files.wordpress.com`
3. type `a` (now the input value is `fa`)
4. see: `facebook.com`
5. `backspace` (back to `f`)
6. still see `facebook.com`

First, I'm pretty sure we're supposed to see facebook for 2). Then, 5) should bring use back to 2). Also, when typing `f` for the first time, we can see `facebook.com` appearing for a few milliseconds.

/cc @Gozala

**Comment by Gozala** [comment]
@paulrouget you are right I have introduced regression as history entries were appended instead of prepended: https://github.com/mozilla/browser.html/commit/6922cf1574cb91228021d6f0349d424984aa2999#diff-e2be09daf30f1f20ee5b9737982f3aa3R104

I also noticed that original code was doing something that I think was unintentional (see https://github.com/mozilla/browser.html/commit/6922cf1574cb91228021d6f0349d424984aa2999#commitcomment-10614982) I believe keeping top history results is better than dropping them.


I have submitted pull request with two commits first to fix regression and the second to keep top history results instead:
https://github.com/mozilla/browser.html/pull/310
