### ISSUE TITLE
Multi window handling

### ISSUE THREAD

**Issue by Gozala** [mozilla/browser.html#351]
Currently there are several issues associated with this:

1. #344 
2. #342 
3. #349
4. #350

I think current set up has a fundamental flaw, as it's unable to handle multiple windows. I know we are planning to make browser.html uni-window app but that's a separate topic. Fundamental issue is "where does the code that manages windows lives" in fact I think that code should not be bound to any single window as that window can be closed  sooner than the other windows. As of uni-window apps that window manager script would just need to delegate to the only open window all events to let it handle them.

I think it would make most sense if window manager code could open / close windows and treat them more or less like remote iframes.

**Comment by paulrouget** [comment]
I purposely ignored window management and force the single window mode. We could indeed build a off-window window manager (maybe as a jsm if done in the runtime, or a worker if done in the app).

Not a priority now though.

**Comment by gordonbrander** [comment]
@paulrouget if I understand correctly, the actual issue is that we need to handle things like `about:blank`, `window.open()`, and https://github.com/mozilla/browser.html/issues/342. It's not that we necessarily want to open multiple windows, but that we need to handle these cases somehow (by opening them within current window).

@Gozala please correct if I'm wrong in my assumptions here.

**Comment by paulrouget** [comment]
#342 will be fixed soon. Just waiting for a review (bug 1134106)

What do you mean by `about:blank`?

`window.open()` is supported from an iframe. It just open a new tab. It is not supported from the app.

Basically, we can only have one single instance of a graphene window open. It's because B2G assumes, for historical reasons, there's only one window (it makes no send to have multiple window open in Firefox OS).

Supporting multiple windows in Graphene is possible, but not trivial, so I think we should only work on it once we know for sure that we want to support multiple windows.

**Comment by gordonbrander** [comment]
Hmm, I'm light on details here. @Gozala was saying something about this causing problems with #342 and popup windows.

I'm not currently interested in supporting multiple windows (deal with it later), just want to be able to open links in Graphene as my default.

**Comment by Gozala** [comment]
@paulrouget @gordonbrander I agree that multi window handling is not a priority right now. Although I do think that no ability to manage windows is a large limitation (which we clearly can mitigate by settling on a uni-window API). I merely want to have bugs on file so that graphene can become a decent app runtime someday + to keep those issues in mind for servo runtime.

As of #342 that could be worked around which is what @paulrouget did in #354 that dependns on graphene chages pointed out in the pull request.

**Comment by Gozala** [comment]
servo/servo#7083

**Comment by Gozala** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1198501

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.
