### ISSUE TITLE
Keybindings are broken (since react)

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#37]
STR:
- open browser.html
- open some empty tabs
- click on the content (below the urlbar)
- Keybindings don't work anymore

**Comment by Gozala** [comment]
I do have it fixed locally, I'll send a pull request with this change.

**Comment by Gozala** [comment]
As of why that was the case:

If you want to stay with in react (like I wanted to for keyboard handling & still not sure that's a best way to go) event handlers will be invoked as long as they occur with in the node into which react renders.

The problem you see is that when you under the location bar which body element get's focused and all the keyboard events occur on it which is why root of react does not handles them. Solution I've used was to make sure that body never becomes `document.activeElement` so that react root component will be able to handle keyboard events.

I've also filled a ticket for react here https://github.com/facebook/react/issues/2846

**Comment by paulrouget** [comment]
Works now.
