### ISSUE TITLE
Fix keybindings so they don't conflict with inputs

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#432]
This bug was introduced by https://github.com/mozilla/browser.html/commit/d2e8450d9db474858ee13fd278fb4d5f77efbaf7. We should only be catching delete key for back if we aren't focused in an input field. Not sure how to accomplish that (cc @Gozala)

**Comment by Gozala** [comment]
@gordonbrander There are several options to go about it, either way we need to not handle keyboard events from the editable fields. To do so we can:

1. Make sure that `event.target` is not an input field, textarea etc. In other words in the keybindigs you can define function that returns action if `event.target` is not an input field and return `null` otherwise.
2. We could use `keypress` event instead which won't propagate to upwards from editable fields there for event handler for `backspace` in this case will never be invoked.

I don't quite remember when `keypress` is dispatched and when it is not I think it may not be invoked in all instances we wanted to in which case it won't be a good option.

**Comment by KevinGrandon** [comment]
I was trying to implement something like this, but the problem I ran into was that bubbled keydown events did not contain enough contextual information to filter them out when focused inside of an iframe.

I filed this platform bug to add additional information, but let me know if you have a better idea: https://bugzilla.mozilla.org/show_bug.cgi?id=1176644

**Comment by cvan** [comment]
> I was trying to implement something like this, but the problem I ran into was that bubbled keydown events did not contain enough contextual information to filter them out when focused inside of an iframe.

could you look at the `window` in the event (`e.view`)?

**Comment by KevinGrandon** [comment]
> could you look at the window in the event (e.view)?

I looked and e.view.document.activeElement points to the iframe. I'm not sure if anything provides you with the necessary contextual information yet.

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping this gecko issues open.
