### ISSUE TITLE
Use iframeElement on mozbrowseropenwindow

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#475]
The `mozbrowseropenwindow` event might come with an `iframeElement` property than runs in the same process as the initial window.

It happens for example if a web page opens a new page with the same origin and with `window.open`.

**Comment by Gozala** [comment]
I have submitted #569 with a hacky fix that has workarounds for:

- Workaround #566 and present desired API by boxing frame in a string instance that is later unboxed by an IFrame react component.
- Workaround #567 by setting a flag on iframe so that implementation of `IFrame` won't call `zoom` on it.
- Workaround #568  by setting a flag on iframe so that implementation of `IFrame` won't call `setVisible` on it. 
- Workaround #564 by creating a type `Force.Action` so that actions boxed with it will force render loop to run sync in the same tick.

**Comment by paulrouget** [comment]
We should fix all of that in gecko first then.

**Comment by paulrouget** [comment]
> We should fix all of that in gecko first then.

If not possible, we can land this workaround.
