### ISSUE TITLE
Why do we box actions in a Webview.Action vs having an id field?

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#498]
@Gozala this is not so much a bug as it is a question. Seems like boxing actions in an action this way causes complexity, since we have to un-box actions in some cases but not others (see `update()` in `synthesis-ui.js`).

I'm curious why we take this approach instead of giving WebView actions a `target` field:

    Record({
      target: Maybe(ID),
      ...
    })

**Comment by Gozala** [comment]
1. Boxing strategy uses `address.forward(x => box(id, x))` vs passing & then capturing `id` in each event handler. Former is optimized & has room to reuse while later dies not.
2. Adding `id` field seems simpler but it is not it just hides complexity. What if action is targeted at active item regardless of Id ? Then we need special id like `@selected`. What if general action is targeted at singular item that has no id say `focus` at url-bar ? Do we create yet another special id ? With boxing it is trivially simple you box any action into a type that carries info about action target (that may include extra info like `id` or not.
3. Branching in `update` became trivial `instanceof` tells you who to delegate before we needed special `isTypeOf` for that + each component had it's own clone of focus / blur / change action types

Now that being said current state isn't perfect in particular the fact that some actions may or may not be wrapped in `WebView.Action` and likely it should be fixed by making things more obvious and wrapping actions in `WebView.ByID({action, id})` or `WebView.BySelected({action})` that way there will be no actions that may or may not be wrapped. Also helper functions could be exposed from modules to make thing little easier lke there's no reason why we can't have `WebView.FocusSelected()` or `WebView.SelectByID(id)` for that matter.

**Comment by Gozala** [comment]
One more thing about boxing is that it can be of arbitrary depth that help routing actions to arbitrary debth by unboxing while assigning id just gives you +1 level. In other words we would not be able to have two web-view-decks without significant changes while with current boxing approach it will be trivial (not that we need that :)

P.S: updated architecture doc in repo covers this in further deatail ;)

**Comment by gordonbrander** [comment]
Cool! Makes sense.
