### ISSUE TITLE
Add web progress events to Browser API

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#53]
Today, the browser API only tells if a frame is loading or not. It makes it impossible to build a progress bar.

**Comment by andreasgal** [comment]
Actually Gordon had an opinion on this. I think he said progress bars are kinda lame anyway and not what people expect from a "speedy" browser. Ask him for the details.

**Comment by gordonbrander** [comment]
...It was more that progress bars should be designed according to what we know about human perception of time (Cog Sci).

Having a way to be notified of progress would be useful, but I'm not sure if it's possible. My understanding is that a lot of HTTP will just be indeterminate until it's finished. However, this doesn't stop Chrome and Safari from faking it.

I would like to use progress bars as well, because they give us more opportunity to "engineer time", as compared to spinners. There is more visual change, which if handled correctly can make wait times feel shorter. They also give us the chance to tell the user "hey, this isn't frozen, just slow".

**Comment by paulrouget** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1125713

**Comment by paulrouget** [comment]
Fixed by bug 1125713. But it's most likely that we won't use this. It's really broken.
