### ISSUE TITLE
Timeout for ctl shift tab should be slightly longer than for ctl tab

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#605]
...because it's harder to ctl shift tab quickly then it is to ctl tab.

**Comment by Gozala** [comment]
What timeout ? We don't have any timeouts in other case. We change an active tab when you release `ctrl` key pretty much how OS X does it but with `cmd` key.. If you never release you'll stay in `select-web-view` as long as you keep `ctrl` pressed.

I'm going to close this, but feels free to reopen if you'd like to do something here. Closing because this way if we need to do more it will likely to happen sooner if we just keep this open.
