### ISSUE TITLE
Opening target="_blank" no longer works

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#635]
Try clicking the link to https://w3c.github.io/requestidlecallback/ on this page: https://plus.google.com/+IlyaGrigorik/posts/bPNjgMwcMKs.

After you click the link, try zooming out. You will see the interface is broken... wrong theme colors, etc.

**Comment by Gozala** [comment]
Simplified test case by creating a following link: `data:text/html,<a%20target="_blank"%20href="https://w3c.github.io/requestidlecallback/">link</a>`

Or just use this <a target="_blank" href="https://w3c.github.io/requestidlecallback/">link</a>

**Comment by Gozala** [comment]
Hmm looks like it's something specific to g+ not just `target='_blank'`

**Comment by Gozala** [comment]
Ok it looks like the issue was that g+ catches those links and calls something like `window.open()` which is causes events with `url: ''` that then fails to parse with `URL` causing exceptions. Odd UI state is actually caused by `if (!state.uri) return null` that renders nothing so we end up without overlay on top of dashboard who's background color appears white.

I also created this url to make testing this easier:

`data:text/html,<script>onOpen%20=%20function()%20{%20win%20=%20window.open()%20};%20var%20onClose%20=%20function()%20{%20win.close()%20}</script><button%20onclick='onOpen()'>Open</button>`
