### ISSUE TITLE
UX: we should always use a screenshot, not the scrapped content

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#652]
Basically, the cards only work when we get a good representative image. And when we get a good representative image, it's most of the time because the page itself has this big image as a central piece. So a screenshot is as good as using the hero image. Think Medium, Qz, etc.

After experimenting with a screenshot-only version of the cards, I haven't found any case where using the scrapped content is better than using a screenshot.

But, there are many instances where the scrapped content is confusing (see https://github.com/mozilla/browser.html/issues/622).

Let's move to screenshot-only.

@gordonbrander what do you think?

**Comment by gordonbrander** [comment]
@paulrouget yeah I've been thinking the same thing, but to get there we need better screenshots. What's the status on https://github.com/mozilla/browser.html/issues/579?

**Comment by paulrouget** [comment]
@paulrouget yeah I've been thinking the same thing, but to get there we need better screenshots. What's the status on #579?

Haven't worked on it yet.

**Comment by Gozala** [comment]
I'm leaning toward let's make our scraper better so we never have screenshots and that cards we produce are always on point.

**Comment by gordonbrander** [comment]
The key here is "recognition over recall". You want users to be able to understand card at a glance and associate it with the page they just left... without having to use their conscious brain.

This is one of those things you can't learn from a mockup... you have to try it with real-world data. After experimenting with this I'm leaning toward screenshots. It's not about the scraper. There are some cases where a hero image or logo is better than a screenshot, but in most cases the hero image and text are distracting.

However the work isn't lost. There are other places where scraping is useful... for example search results or a bookmarking feature where you have to use recall because you haven't seen the results before..

**Comment by gordonbrander** [comment]
As @Gozala points out, scraper data works better for things like search results, where recognition can't work anyway https://github.com/mozilla/browser.html/issues/610#issuecomment-137343290

**Comment by gordonbrander** [comment]
Does not apply to `perspective-ui`.
