### ISSUE TITLE
Handling animations with react (or rather in our architectural setup)

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#654]
We want to be able to do complex animations, beyond simple CSS transitions:

- CSSKeyframe animations (fixed time)
- Gesture, mouse and scroll-based animations (dynamic time) (example http://lab.hakim.se/scroll-effects/)
- Physics-based spring animations (dynamic time) (example http://fat.gfycat.com/ElatedDistantDrever.mp4)

**Comment by Gozala** [comment]
@paulrouget That spring based scroll into a card view animation looks really rad! I would love if we could integrate into our current design. Could you please also share a code, I think it would be very informative to me.

Unfortunately I have not had any prior experience with doing animations in the UI other than trivial css transitions. As a consequence I did not had any good insight how to integrated them into our current [architecture](https://github.com/mozilla/browser.html/blob/master/docs/architecture.md). Since than though I got some experience by implementing #617 #646, #650 and have learned enough too feel more confident about the approach we could use (or maybe have learned so little that can afford to be naive). 

There for I would really love to see how @paulrouget implemented that animation and see how that could translate into approach used in above mentioned pull requests. I think it would also help a ton if @paulrouget you could look at those pull requests and provide your insight how used approach can or can not handle certain animations cases. It would also help if we scheduled a meeting and just went through these to determine pattern we'll be using in our implementation.

It also needs to be said that approach in the pull requests is not quite what I think we should do as there is one specific problem which I tend to workaround. More specifically things are setup is that **events in the view** layer trigger a state **update** that in consequence triggers a **render** which in turn triggers a **view change** or more specifically DOM mutation. The recurring problem I faced was that `update` function produces a next state and there for that's where knowledge about weather we need more animation frames or not is, also sometimes next state (of the animation) is where certain actions need to be triggered like "close a tab when card is reaches certain threshold" or "go back when swipe is released passed certain threshold" but issue is that `update` is unable to trigger anything or request anything all it can do is return whatever the next state is. I end up making a workaround for these in form of `animate(node, onNextFrame, isAnimating)` so last boolean flag will keep scheduling animations frames as long as it is `true` which typically would be a field in the state signifying if animation is complete yet. The `onNextFrame` callback will trigger action that to step through the animation by triggering update that applies physics onto animated node. In order to workaround that update can not trigger action I instead store action in the state with `update` in the right moment  which then is triggered from `onNextFrame` (if it's `null` such action is dropped).

Now proper solution would be to let update request actions so that view won't need to constraint itself or even have any animation logic in it for that matter. For that I consulted [Elm language](http://elm-lang.org) designer (Elm is actually where our architecture design is borrowed from BTW)  and I got this [nice example](https://github.com/evancz/elm-architecture-tutorial#example-8-animation) in response. To save you from understanding Elm syntax I try to translate general idea into JS. So currently our `update` function signatures looks like `(currentState, currentAction) => nextState` what it should be instead is something more like this `(currentState, currentAction) => [nextState, nextAction]` this would allow `update` to request more animations frames or a `tab close` action without constraining a `view` at all. This unfortunately requires update to our update function signatures which is why I chose to use above described workaround for now.

Moving forward I would really like to try implement some of the interaction animations like ones linked in the description as separate examples with this pattern to see how they actually work out in practice. Ideally I would do integration of them into a browser.html UI as separate step. Motivation here is to iterate quickly and defer some of the challenges "like where should my state live" or "how do I avoid obsolete re-rendering"  till later.

**Comment by Gozala** [comment]
Once thing I forgot to mention that with outlined pattern applying easing or springiness to an animation becomes very separate problem that can be solved with a completely independent library (as illustrated in the Elm's animation example) that just deals with interpolating numbers over time.

**Comment by Gozala** [comment]
To be fare there are still some challenges with doing animations that are specific to our architecture (and sometimes to react general):

1. How do we make sure that we do absolutely minimum. Every state update triggers top level view re-render and ideally update only animated node. Is the overhead of doing it negligible (I don't yet know) ? If it is not we may need to avoid going through the full update + render pipeline, I have some ideas but not baked enough to write examples.

2. Sometimes other updates happen concurrently with our animations and there for can cause junk (I see a lot of it during page load although not sure if it's update or maybe a progress bar transition or even something deep in the platform that has to deal with loading content in the iframe). If other updates during animation is a problem maybe we could defer them ? Or maybe we can time our update / render cycles and depending on that make render scheduler smarter ?

3. Where do we store state related to animations (like position velocity etc...) it usually not obvious and usually you don't want to mix it with state of the view being animated itself. I have some thought about that too which are same as thoughts for No 1.

**Comment by paulrouget** [comment]
I don't know about the React part, but if we want to do some advanced animations, we need to drive them in JS. And these animations needs to be compose-able. I'm sure there are plenty of JS lib that do that.

The spring animation used in my animation is a spring RK4 effect: http://mtdevans.com/2013/05/fourth-order-runge-kutta-algorithm-in-javascript-with-demo/

We could imagine adding a CSS `timing-function` that does this kind of animations, but then that would make the animation duration variable (`animation-duration` would not work).

**Comment by gordonbrander** [comment]
There have been several proposals for CSS spring animations and other animations that are not fixed time. It would be amazing to do this at the platform level. Spring animations are a big part of contemporary native UI design.

**Comment by Gozala** [comment]
We should keep on eye on work being done by @[chenglou](https://twitter.com/_chenglou) he's a react contributor and seem to focus he's work on animations:

- https://gist.github.com/chenglou/40b75d820123a9ed53d8
- https://medium.com/@chenglou/react-motion-and-animated-4b3edf671cba

**Comment by gordonbrander** [comment]
This is done.
