### ISSUE TITLE
Does the 16ms rendering warning also happen in animation.js?

### ISSUE THREAD

**Issue by paulrouget** [mozilla/browser.html#658]
I was wondering if `Animation.run` would also warn use if it takes more than 16ms to execute.

@Gozala?

**Comment by Gozala** [comment]
@paulrouget it should since all the DOM manipulations end up going through the same render function. That being said there is a thing that currently is not captured by those warnings!

I'll try to explain what is going on at the JS level and what is currently measured and what is not. In our code we have two concurrent loops:

1. update loop
2. render loop

Turn on update loop is triggered by `address.receive(action)` call that only occurs in response to DOM event and causes `update(state, action)` to produce a next state. This is typically very fast and does not involves  any DOM access other than reading some details from `event` that triggered it. At the end of it's turn `render` is scheduled in the `render` loop. Scheduling a `render` multiple types in the same turn of `render` loop has no effect. Turns of `update` loop are not timed and produce no warnings.

2. Render loop as mentioned above is scheduled in effect to state update (if update returned same state no render is scheduled, if multiple updates scheduled with in the turn still only one more turn will take place). Render loop turns happen only on animation frame, in other words once turn is scheduled animation frame is requested that will cause a turn. On turns of "render loop" calls to `React.render(element, state)` take place which is when react does all of it's work that includes calling most our view functions, diffing against previous virtual dom and also patching actual DOM tree. This is where most of our time is spend and most garbage is produced. Turns are timed here and if turn takes more than `16ms` warring is logged.

Now in terms of `Animation.run` only thing it does is causes a turn of "update loop" to recompute next state of animated entity. Actual work is still done in `render loop` that runs independently of the update loop so if updates during animation loop take longer than `16ms` that would still be captured by warnings.

Unfortunately there was an exception introduced to workaround the unfortunate `mozbrowseropenwindow` API that requires iframe to be inserted into document in the same tick. Which is if `address.receive` is passed a `Force(action)` that would cause `render loop` to turn right after `update loop` instead of scheduling a turn. That should have no effect on animations though.

**Comment by Gozala** [comment]
Warnings now capture all of the time from spend from receiving an event to actually rendering it.
