### ISSUE TITLE
Switching tabs should happen after releasing key

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#82]
What happens:
- Right now `ctl+tab`, `cmd+shift+[`, `cmd+shift+]` all switch tabs immediately.
- There is lots of flickering jankiness

What should happen:

1. Press keyboard shortcut, tab shade is shown.
2. New active tab is highlighted
3. Page is switched when keys are released.

Hitting key command multiple times before releasing should change active highlighted thumbnail, but page should not switch until you release.

Let's make `ctl+tab` and `cmd+shift+[/]` behave the same way. Show tab shade, change active thumbnail, change active site when all keys are released.

- [x] Page should not switch until keys are released
- [x] `ctl+tab` and `cmd+shift+[` and `cmd+shift+]` should highlight next/prev tab and change location field
- [ ] Tab shade shows after short 150ms delay so you can switch between pages rapidly without seeing shade.
- [x] Hovering over tabs should change location field text

**Comment by Gozala** [comment]
@gordonbrander Are you sure making `cmd+shift+[` switch the tap immediately is good idea ? To me tabswitch seems very similar to OS X app switcher & there for I have built-in expectation for it to behave the same:

`cmd+[` selects next app but only switches to it when I release `cmd`, which is pretty much what you described for `ctrl+tab`.

**Comment by gordonbrander** [comment]
It's a hypothesis. The ergonomics of holding and releasing 3 keys with 2 hands is different from holding and releasing 2 keys with 1 hand. Try it in the current build. Do you think it feels ok? Bad? Why?

However, we can start with having same behavior in both instances and refine from there.

**Comment by Gozala** [comment]
@gordonbrander actually dismiss what I've said `cmd+[` does nothing on OSX I was thinking of `cmd+tab`.

**Comment by Gozala** [comment]
Worked under #87

**Comment by gordonbrander** [comment]
- Colors should change only when page changes
- Tab shade should show after 150ms delay. So if I `ctl+tab` quickly, the page is immediately switched. If I hold down `ctl+tab` for 150ms, then tab shade is shown

**Comment by Gozala** [comment]
me and @gordonbrander spend quite some time looking into the issue that was reproducible by clicking `control tab` keys really fast. We had different guess what could have being cousin it & there is an archive of the discussion here https://browserhtml.slack.com/archives/general/p1424744707000607


After looking into this further, I can say I have a logical explanation of observed behavior. This is what is going on there. To start with here a trace of the events when the bug occurs:

```js
// 1. ! render
{ tabStrip: {isActive: false},
  webViewers: [{id: 0, isSelected: true, isActive: true },
               {id: 1, isSelected: false, isActive: false}]}

// 2. ! keydown: 'control tab' @ 397537859

// 3. ! update in .webViewers
{ tabStrip: {isActive: false},
  webViewers: [{id: 0, isSelected: false, isActive: true },
               {id: 1, isSelected: true, isActive: false}]}

// 4. ! update in .tabStrip.isActive
{ tabStrip: {isActive: true},
  webViewers: [{id: 0, isSelected: false, isActive: true },
               {id: 1, isSelected: true, isActive: false}]}

// 5. ! keyup: 'control' @ 397537915

// 6. ! update in .tabStrip.isActive
{ tabStrip: {isActive: false},
  webViewers: [{id: 0, isSelected: false, isActive: true },
               {id: 1, isSelected: true, isActive: false}]}

// 7. ! keyup: 'tab' @ 397537962

// 8. ! render
{ tabStrip: {isActive: false},
  webViewers: [{id: 0, isSelected: false, isActive: true },
               {id: 1, isSelected: true, isActive: false}]}
```

Here is an explanation of the trace of events:

1.  First normal stat was rendered, where tabstrip isn't visible and first tab is both selected and active.
2. `control tab` key was pressed.
3. `control tab` key handler triggered an update in the `webViewers` that marked first tab unselected and second one selected.
4. `control tab` key handler toggled a tabstrip visibility, causing a `.tabStrip.isActive` to become `true`.
5. `control` key was released.
6. `control` keyup handler was triggered which toggled tabstrip visibility, causing a `.tabStrip.isActive` to become `false`.
7. `tab` key was released.
8. Request animation finally caused rendering of a new state.

Clearly there is a an update missing that would flip `isActive` field of both tabs. The it was not filed is because code doing it invokes `webViewersCursor.update(activate)` which in turns find tabs that has `isActive: true` and sets it to `false` & also finds a tab that has `isSelected: true` and makes it's `isActive: true`. Anyway what happens is that because keyup event handler happened before render did, all the event handlers were still bound to a state from a previous render, where `isActive` and `isSelected` where true on the same tab, there for `activate` did nothing, which is why there was no update for it in the trace & also why we end up rendering incorrect state.

**Comment by Gozala** [comment]
So immediate solution that would work would be to disable animation frame and cause render loop right away, that way render will be triggered before keyup handlers will and there for keyup handler will have a pointer to an up to date state.

Which is what I'm going to do for now, while seeking a solution how to fix this with animation frame enabled.

**Comment by gordonbrander** [comment]
Looks great. I think we should forget about the `150ms` delay for now and land this when ready.

We can file a second bug for the delay and deal with it way later on. That part is definitely not crucial to the MVP.

**Comment by gordonbrander** [comment]
Added https://github.com/mozilla/browser.html/issues/139 to track delay thing.

**Comment by gordonbrander** [comment]
Closed by https://github.com/mozilla/browser.html/commit/fa5331e227c6935bce3a238ac5ae16d8781e780e.
